# Dependencies
markdown:         redcarpet
#pygments:         true
highlighter:      true

# Permalinks
permalink:        pretty

# Setup
title:            sdorsett.github.io
tagline:          'Things I find interesting'
description:      ''
url:              http://sdorsett.github.io

author:
  name:           'Stan Dorsett'
  url:            https://twitter.com/standorsett

paginate:         5
plugins:          [jekyll-paginate]

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/sdorsett
